--v=0
--random_seed=1
--data_source=0
--path_to_output_bag=/home/suhang/projects/event_imu_velometer/data/simulation.bag

--contrast_threshold_pos=0.5
--contrast_threshold_neg=0.5
--contrast_threshold_sigma_pos=0
--contrast_threshold_sigma_neg=0

--exposure_time_ms=12.0
--use_log_image=1
--log_eps=0.001

--calib_filename=/home/suhang/esim_ws/src/rpg_esim/event_camera_simulator/esim_ros/cfg/calib/pinhole_mono_nodistort.yaml

--renderer_type=2
--renderer_scene=/home/suhang/esim_ws/src/rpg_esim/event_camera_simulator/imp/imp_opengl_renderer/resources/objects/flying_room/flying_room.obj
--renderer_zmin=0.3
--renderer_zmax=40.0

--trajectory_type=0
--trajectory_length_s=20.0
--trajectory_sampling_frequency_hz=5
--trajectory_spline_order=5
--trajectory_num_spline_segments=20
--trajectory_lambda=0.05
--trajectory_multiplier_x=1.0
--trajectory_multiplier_y=1.0
--trajectory_multiplier_z=0.5
--trajectory_multiplier_wx=0.3
--trajectory_multiplier_wy=0.3
--trajectory_multiplier_wz=0.3
--trajectory_offset_z=0.0

--simulation_minimum_framerate=30.0
--simulation_imu_rate=1000.0
--simulation_adaptive_sampling_method=1
--simulation_adaptive_sampling_lambda=0.5
--simulation_post_gaussian_blur_sigma=0.0

--simulation_imu_bias_mode=zero
--simulation_imu_gyr_bias_noise_sigma=0.0
--simulation_imu_acc_bias_noise_sigma=0.0
--simulation_imu_gyr_noise_sigma=0.0
--simulation_imu_acc_noise_sigma=0.0
--simulation_imu_gyr_bias_init_x=0.0
--simulation_imu_gyr_bias_init_y=0.0
--simulation_imu_gyr_bias_init_z=0.0
--simulation_imu_acc_bias_init_x=0.0
--simulation_imu_acc_bias_init_y=0.0
--simulation_imu_acc_bias_init_z=0.0
--simulation_imu_bias_samples=100
--simulation_imu_bandwidth_hz=200
--simulation_imu_gravity_magnitude=9.81

--ros_publisher_frame_rate=30.0
--ros_publisher_depth_rate=30.0
--ros_publisher_optic_flow_rate=30.0
--ros_publisher_pointcloud_rate=0
--ros_publisher_camera_info_rate=10
